id = "colored-zed-icons-theme"
name = "Colored Zed Icons Theme"
version = "0.4.0"
schema_version = 1
authors = ["TheRedXD", "Zed Industries <support@zed.dev>"]
description = "Default Zed icons, but colored!"
repository = "https://github.com/TheRedXD/zed-icons-colored-theme"
